use std::{fs::write, path::PathBuf};

use anyhow::{Context, Result};
use chariot_config::lua::{EMBEDDED_LUA_FILE_BUILTINS, EMBEDDED_LUA_FILE_HELPERS, EMBEDDED_LUA_FILE_META};
use chariot_util::fs::make_path;
use log::info;

const LSP_SUPPORT_DIR: &str = ".chariot-lsp-support";

pub fn setup_lua_lsp() -> Result<()> {
    let lsp_support_dir = PathBuf::from(LSP_SUPPORT_DIR);
    make_path(&lsp_support_dir).context("Failed to make LSP support directory")?;
    for (filename, contents) in [
        ("builtins.lua", EMBEDDED_LUA_FILE_BUILTINS),
        ("helpers.lua", EMBEDDED_LUA_FILE_HELPERS),
        ("meta.lua", EMBEDDED_LUA_FILE_META),
        (".gitignore", "*\n../.luarc.json"),
        (
            "README.txt",
            "This directory (and files within) is generated by chariot for lua lsp (LuaLS) integration.\nIt can and will fall out of date over time, at which point it should be re-genereated.\nShould not be committed to git.",
        ),
    ] {
        let filepath = lsp_support_dir.join(filename);
        write(&filepath, contents).with_context(|| format!("Failed to write `{}`", filepath.display()))?;
    }

    write(
        ".luarc.json",
        format!(
            "{{
    \"$schema\": \"https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json\",
    \"workspace.library\": [\"{}\"],
    \"workspace.ignoreDir\": [\".chariot-cache\", \".chariot-rootfs\"],
    \"workspace.useGitIgnore\": true,
    \"runtime.builtin\": {{
        \"basic\": \"enable\",
        \"coroutine\": \"disable\",
        \"debug\": \"disable\",
        \"io\": \"disable\",
        \"math\": \"enable\",
        \"os\": \"disable\",
        \"package\": \"enable\",
        \"string\": \"enable\",
        \"table\": \"enable\",
        \"utf8\": \"disable\"
    }}
}}",
            LSP_SUPPORT_DIR
        ),
    )
    .context("Failed to write .luarc.json")?;

    info!("Generated `.luarc.json` and `{}`", LSP_SUPPORT_DIR);

    return Ok(());
}
