name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Get Deps
      run: |
        sudo apt-get update && sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --release --locked --target x86_64-unknown-linux-musl
      env:
        CC_x86_64_unknown_linux_musl: musl-gcc

    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        [ -z "$(git tag --points-at HEAD --list '????-??-??')" ] || exit 0

        mv target/x86_64-unknown-linux-musl/release/chariot chariot-linux-x86_64

        tag="$(date -u +%Y-%m-%d)"
        gh release create "$tag" chariot-linux-x86_64 \
          --title "$tag"                              \
          --target "$GITHUB_SHA"                      \
          --prerelease                                \
          --latest=false                              \
          --generate-notes
